#-------------------------------
# General Site Settings
baseURL = "/"
languageCode = "en-us"
title = "Gus Reid | Move True"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 12


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

  [[menu.main]]
    name = "Classes"
    url = "/classes/"
    weight = 2

  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 4

  [[menu.main]]
    name = "Work With Me"
    url = "/work-with-me/"
    weight = 3

  # Call to action button
  [params.cta_button]
    enable = true
    cta_button_link = "https://www.paypal.com/donate/?hosted_button_id=NS545HRZ5LQYA"
    cta_button_text = "Donate Now"


[params]
  logo = "/"
  description = "Danto is a news and magazine Hugo theme"

  footer_logo = "colored-logo.png"

#Article page setting
  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "Thoughts, meanderings and musings."  #heading
    hero__description = ""    #paragraph


  #-------------------------------
  # Tags Section Settings
  [params.tags_section]
    enable = true
    number_posts = 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
    number_columns = 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.

 # [[params.tag]]
 #  tag = "post"

  # You can add many tag sections to the homepage; each section will show the recent posts by the tag.


  #-------------------------------
  # Authors Section Settings
  [params.authors_section]
    enable = true
    section_title = "Meet our authors"


  #-------------------------------
  # Footer Settings
  [params.footer]
    footer__description = ""

  # Social Links
  [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://www.instagram.com/gustamove/"

  [[params.social]]
    icon = "ion-logo-youtube"
    name = "Youtube"
    link = "https://youtube.com/@thegusreid?si=Yw58YHu1vNPaPvK4"

  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://x.com/TheGusReid?s=09"

  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/


  # Newsletter
  [params.mailchimp]
    enable = true
    mailchimp__title = "Sign Up Now"
    mailchimp__description = ""
    mailchimp__identifier = "/"
    mailchimp__input__text = "Your email address"
    mailchimp__button__text = "Sign Up"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "your@email.com" # Add your form_id

    # NOTE
    # Danto comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[taxonomies]
  author = "authors"
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
